no change     /data/nathalie_maria_kirch/anaconda3/condabin/conda
no change     /data/nathalie_maria_kirch/anaconda3/bin/conda
no change     /data/nathalie_maria_kirch/anaconda3/bin/conda-env
no change     /data/nathalie_maria_kirch/anaconda3/bin/activate
no change     /data/nathalie_maria_kirch/anaconda3/bin/deactivate
no change     /data/nathalie_maria_kirch/anaconda3/etc/profile.d/conda.sh
no change     /data/nathalie_maria_kirch/anaconda3/etc/fish/conf.d/conda.fish
no change     /data/nathalie_maria_kirch/anaconda3/shell/condabin/Conda.psm1
no change     /data/nathalie_maria_kirch/anaconda3/shell/condabin/conda-hook.ps1
no change     /data/nathalie_maria_kirch/anaconda3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /data/nathalie_maria_kirch/anaconda3/etc/profile.d/conda.csh
no change     /data/nathalie_maria_kirch/.bashrc
No action taken.

CondaError: Run 'conda init' before 'conda activate'

Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/data/nathalie_maria_kirch/anaconda3/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/data/nathalie_maria_kirch/anaconda3/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/data/nathalie_maria_kirch/anaconda3/lib/python3.12/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/data/nathalie_maria_kirch/anaconda3/lib/python3.12/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'
slurmstepd: error: *** JOB 1576013 ON compute-permanent-node-990 CANCELLED AT 2024-08-06T15:02:37 DUE TO TIME LIMIT ***
